### ISSUE TITLE
Banner with new design for FB group

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-design#14]
Now that we have a new design for 2018, it would be nice to update the banner in the FB group accordingly: https://www.facebook.com/groups/godotengine/

**Comment by djrm** [comment]
i already did it but im not sure about the sizes, can someone test it, i dont have facebook.

![banner](https://user-images.githubusercontent.com/1103897/34840206-e7adbb50-f6c9-11e7-84bc-08e4b7d9b661.png)

**Comment by akien-mga** [comment]
The current display seems to be 820x332 (±2 px, I cropped a screenshot without being very thorough to get it :)).

**Comment by akien-mga** [comment]
So the current one is a bit too wide and need to be a big higher. FB does something pretty weird I try to use it though (it zooms in, but much more than would be needed to fit it in height):
![image](https://user-images.githubusercontent.com/4701338/34847015-434f34c0-f71a-11e7-9a50-3b8a0bb2dd2d.png)

**Comment by akien-mga** [comment]
I used banner.svg and exported it to 150 DPI, it looks relatively good now (almost like your initial proposal here): 
![image](https://user-images.githubusercontent.com/4701338/34867390-3ac644c2-f780-11e7-8965-ad8a0fc32fe0.png)

There are still some compression artifacts, but I don't know of a way around it, it's just how FB reduces quality on all images to save space..

**Comment by akien-mga** [comment]
BTW, various users expressed that they'd like to have a wallpaper with this design :)

**Comment by groud** [comment]
I like this color scheme a lot ! @djrm, would mind trying to use it for the shirt too ?
Event if it's one color more, this design highlights the logo a lot more that the current version :)

**Comment by djrm** [comment]
@groud yeah, i would also preffer that, i was trying to reduce the colors so, it is going to be 3 colors now, if thats acceptable, please tell me, and give like 1 or 2 hours.

**Comment by djrm** [comment]
@akien-mga ok, will try to make a nice wallpaper with this

**Comment by djrm** [comment]
@groud t-shirt with 3 colors

![godot_tshirt_2018](https://user-images.githubusercontent.com/1103897/34894199-0dee405a-f7a6-11e7-8172-e29858628ae0.png)

**Comment by akien-mga** [comment]
@djrm We discussed it with @AndreaCatania but we fear that the colors used will be too close to the navy color of the T-shirt, so the contrast won't be good. Also the Godot head blue is finally quite similar to the other blue (albeit different), so it's almost like 2 colors :P

So contrast-wise I'd be more for https://github.com/godotengine/godot-design/blob/master/assets/2018/godot_tshirt_2018.svg, but we still have until tomorrow morning (when I'll pay and confirm the order) to decide on the final final design.

CC @NathanLovato for some feedback: do you prefer the above design (3 colors on navy textile), or https://github.com/godotengine/godot-design/blob/master/assets/2018/godot_tshirt_2018.svg (2 colors on navy textile)?

**Comment by djrm** [comment]
to be honest i like the white version better because im sure it will look good (and be visible) in any dark textile, and thats the problem with using blue, that i dont know the target and i cant make an adequate design. so if you want to go for the best possible outcome, go for the white version.

**Comment by akien-mga** [comment]
Yeah I agree, let's go with the 2-color white design.
