### ISSUE TITLE
Missing recommended CC-By mention to use

### ISSUE THREAD

**Issue by NathanLovato** [godotengine/godot-design#18]
The repo is cc-by but it doesn't say who you should credit and where you should link? 
For the Godot presentation reskin right now I've used `CC-By 4.0 Daniel Ramirez - https://github.com/godotengine/godot-design` on Youtube. Is it okay?

![image](https://user-images.githubusercontent.com/12694995/38453068-94b53cfc-3a8a-11e8-9c84-829a540221aa.png)

**Comment by djrm** [comment]
Im not really sure, now there is content from other people in this repo, maybe a file with credits would be nice to have, so people can credit the respective authors.

and @NathanLovato about the credits yeah that seems to be okay.

**Comment by fire** [comment]
What is needed to close this issue?

**Comment by NathanLovato** [comment]
I think it's fine, there are CC-By mentions on the docs and some other places, that should do it.

**Comment by fire** [comment]
Thanks.
