### ISSUE TITLE
Updating branding assets on Steam store page

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-design#20]
I'm in the process of reworking our [Steam store page](https://store.steampowered.com/app/404790/Godot_Engine/) which is quite outdated by now, uploading new videos/screenshots, tweaking the description, and most importantly changing the logo for the new Godot 3 logo.

![image](https://user-images.githubusercontent.com/4701338/40232922-25a65e0e-5aa1-11e8-8af7-8d6ff15db2cf.png)

For the latter part, I'd welcome some help (from @djrm? :)) to make good looking assets in the dimensions needed by Steam for the various uses:

![screenshot_20180518_134225](https://user-images.githubusercontent.com/4701338/40232964-4d93783e-5aa1-11e8-9caa-07169ea5c083.png)

![screenshot_20180518_134253](https://user-images.githubusercontent.com/4701338/40232976-5e175af4-5aa1-11e8-9960-ad69cef7d116.png)

![screenshot_20180518_134327](https://user-images.githubusercontent.com/4701338/40233000-7244863c-5aa1-11e8-9f35-577aafcd9aa4.png)

Here's the template provided by Valve for all the required sizes mentioned above: https://partner.steamgames.com/public/marketing/game_page_templates_v3.zip

Also interesting, they have a "Artwork Override" system where we could register different sets of artwork, and swap them as needed when we want to promote something specific. Not sure we'd have a use case right now but it's good to know :)

**Comment by akien-mga** [comment]
I made some quick and dirty capsule images as I want to update the Steam page now. I'd still be interested in some more thought-out images, so I'll leave this issue open, and once we have a nice concept, I can update the Steam page.

![616x353](https://user-images.githubusercontent.com/4701338/40857451-7af33ad6-65db-11e8-835f-4a638cb50672.png)
![467x181](https://user-images.githubusercontent.com/4701338/40857452-7cb50174-65db-11e8-94c7-d883b2301db0.png)
![460x215](https://user-images.githubusercontent.com/4701338/40857456-7e55c0fe-65db-11e8-83a2-218066a1784c.png)
![231x87](https://user-images.githubusercontent.com/4701338/40857457-7ff8a5b6-65db-11e8-837b-df2b88d65006.png)

(and yeah, the background has compression artefacts, I used a picture @reduz uploaded to Twitter which got converted as JPG).

**Comment by aaronfranke** [comment]
Is there anything else that needs to be done? The store page looks quite good as-is.

**Comment by fire** [comment]
If display the version number, every time we update we'll be forced to change the version number. Changing only images is easier.

**Comment by fire** [comment]
No changes from Akien since 2018, so closing. Please make a new issue if you want to change the steam page :).
