### ISSUE TITLE
Can we get just a stock logo with a transparent background? Like a press kit.

### ISSUE THREAD

**Issue by exts** [godotengine/godot-design#23]
For people that want to use it in art for blogs, games, etc... to represent godot. Right now you kind of have to take a wild guess which of the svg's in the repo has the logo by itself then just crop it from one of those images.

Should add a little press kit that people can use.

**Comment by akien-mga** [comment]
Here you go: https://github.com/godotengine/godot/blob/master/logo.svg

**Comment by fire** [comment]
See https://github.com/godotengine/godot/issues/8514 's  [presskit](https://github.com/godotengine/godot/files/1353202/presskit.zip)

It make sense to import the zip contents into this repository.

**Comment by fire** [comment]
Missing tasks from the other issue.

```
Logo usage guidelines
Engine screenshots
Game/showcase screenshots
Info text
Add to website
```

**Comment by fire** [comment]
Original issue was resolved. Another will can be opened about a Godot Engine presskit.
