### ISSUE TITLE
Have the ability to select the viewport type on start

### ISSUE THREAD

**Issue by rezgi** [godotengine/godot-design#41]
Hello,

 I was thinking it would be nice to have for example the 2D or script viewport on launch of Godot, so maybe add the option in Project Settings to start Godot with selected viewport.

**Comment by akien-mga** [comment]
This is not related to the visual identity of Godot :)

Such issues should be opened on https://github.com/godotengine/godot (make sure to follow the issue template there).

**Comment by rezgi** [comment]
Well seems to me it's related to Godot user experience, but ok thanks !

**Comment by akien-mga** [comment]
This repo is about visual design (icons, etc.), not about UX.

**Comment by akien-mga** [comment]
I see that the readme states otherwise, but it's wrong, I'll fix that ;)

**Comment by rezgi** [comment]
Ok at least I helped in that ! :D
