### ISSUE TITLE
Icon optimization - spaces around negatives?

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot-design#44]
The [README](https://github.com/godotengine/godot-design/blob/master/README.md) contains this section:

> Editor icons must be first optimized before being added to the engine, to do so:
> * Add them to the "/engine/icons/svg" folder.
> * Run the "optimize.py" script (you must have `scour` installed).

However, when I run `python3 optimize.py`, it results in over 300 changed files. Looking in my git client, it appears that they are all removals of spaces around negative numbers:

![Zoomed in removal of spaces around negative decimal number](https://user-images.githubusercontent.com/1646875/62981368-e17d0600-bddd-11e9-835d-55fdb1c7983e.png)

So, what's up with this? Is this intended behavior? If so, why aren't the fixed versions committed in the repository?

**Comment by Calinou** [comment]
@aaronfranke Is this still relevant with the move to svgcleaner?

**Comment by aaronfranke** [comment]
@Calinou It's not, but the icons in this repository don't use svgcleaner. If #52 is closed, this can be too.
