### ISSUE TITLE
Change color of 3D node icons from red to something else

### ISSUE THREAD

**Issue by starry-abyss** [godotengine/godot-design#54]
Red is the color I'd like to see when some serious error occured.
Also it might be a problem for colorblind people who might not easily distinguish red and green.

How about changing it in all default themes (from Godot 4.0 on)?
Not sure what is a better color to use for 3D node icons instead, perhaps, orange or yellow?

**Comment by Calinou** [comment]
I'm not sure about this; I like the RGB analogy as it is (for 3D, GUI and 2D nodes respectively).

We can consider adjusting the hue slightly for accessibility reasons, but I'd like to see screenshots of the editor with colorblind filters to prove there's an issue first.

**Comment by starry-abyss** [comment]
For me it's rather psychological, as red is an attention-grabbing color.

> I like the RGB analogy

RGB analogy is good for axis coloring (also three and the order is the same), but as it comes to node types, there are also white, purple, rainbow-colored nodes, etc. I don't really see any analogy here.

And looks like yellow is currently used for some resource types.

> We can consider adjusting the hue slightly for accessibility reasons, but I'd like to see screenshots of the editor with colorblind filters to prove there's an issue with the current colors first.

Here you are (the left part is the original Godot). In the first two we see troubles differentiating between red and green (look especially at buttons at the left of the window suggesting to create a root node), and in the 3rd one it even more complicating than the originally proposed change, as there are troubles differentiating blue and green. However, the last filter shows that the brigthness is also too close.

That said, all of these might not be a huge problem for colorblind people, as long as icons themselves (shapes) are different enough (so just plain circles is bad). Moreover, category differentiation may probably not be a major issue in the first place.

![2020-01-23_20-50](https://user-images.githubusercontent.com/11571820/73009759-3196d480-3e22-11ea-9bdd-ea6a45a602e4.png)

![2020-01-23_20-36](https://user-images.githubusercontent.com/11571820/73008808-64d86400-3e20-11ea-8032-50f83711fc99.png)

![2020-01-23_20-36_1](https://user-images.githubusercontent.com/11571820/73008822-686beb00-3e20-11ea-9c69-c6e90c3d779d.png)

![2020-01-23_20-51](https://user-images.githubusercontent.com/11571820/73009771-36f41f00-3e22-11ea-8015-c637d99a2c8c.png)

**Comment by Calinou** [comment]
@starry-abyss I think it makes sense to distinguish icons by shape if there can be ambiguity, but I'm not sure how to do it exactly.

Could you make a mockup for Node2D, Node3D (ex-Spatial) and Control?

**Comment by starry-abyss** [comment]
Maybe someone else helps with that? :)
I only went here to ask to remove lots of red by default (and got the negative answer)...
