### ISSUE TITLE
Slight Godot Logo Redesign.

### ISSUE THREAD

**Issue by Knalco** [godotengine/godot-design#55]
**I know, I know... the logo is not to be redesigned right now.** 
 But I just liked the way this one turned out and wanted to share it with the community.

![logo_Godot](https://user-images.githubusercontent.com/36607027/75033370-a81b0680-54a2-11ea-9b87-c9039edff7cc.png)

**Comment by Calinou** [comment]
We don't have plans to change the default Godot logo anytime soon, but thanks for submitting it anyway :slightly_smiling_face:
