### ISSUE TITLE
Godot Video intro

### ISSUE THREAD

**Issue by HolyAcorn** [godotengine/godot-design#65]
Made a little intro with the Godot logo. (:

https://user-images.githubusercontent.com/74989722/114630635-51cae180-9cbb-11eb-8a3b-c20ab7a5f943.mp4

**Comment by Calinou** [comment]
Thanks for your submission :slightly_smiling_face: 

This repository is only used for design elements that we use for "official" promotion of the engine, so I'll have to close this unfortunately.

**Comment by HolyAcorn** [comment]
Hi! Oh, I am sorry, I was unaware of such, but thank you for letting me know! I hope I can contribute to the Godot Engine in some way in the future! (:
