### ISSUE TITLE
Problem with sprite and kinematic_body dark theme

### ISSUE THREAD

**Issue by guilhermefelipecgs** [godotengine/godot-design#8]
Sprite and KinematicBody icons doesn't working in dark theme.

![2017-12-03-125530_69x142_scrot](https://user-images.githubusercontent.com/1387165/33526492-8db01a62-d829-11e7-90d7-277a71e2d41e.png) ![2017-12-03-125547_63x137_scrot](https://user-images.githubusercontent.com/1387165/33526493-8dcdbb80-d829-11e7-944d-9b52a7f486af.png)

**Comment by djrm** [comment]
ok thanks, will fix them.

**Comment by djrm** [comment]
solved by 9dd39df6c833ed894ef2ff421f0fe6a3806177b4
