### ISSUE TITLE
Banner/poster for GodotCon 2018

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-design#9]
We're going to announce GodotCon 2018 which will take place in Brussels, Belgium on 5 & 6 February, and it would be nice to have a specific banner/poster design that we could use in the announcement blog post, on the events page, etc.

For [GodotCon 2017](https://godotengine.org/article/meet-us-fosdem-2017-and-godotcon), @razvanc-r had made this one:
![587f626da0f7f646960937](https://user-images.githubusercontent.com/4701338/33668135-26e1a616-da9f-11e7-824e-672546f1456f.png)
[GodotCon 2017 SVGs.zip](https://github.com/godotengine/godot-design/files/1535606/GodotCon.2017.SVGs.zip)

For [Meet the Nodes](https://godotengine.org/article/meet-nodes-godot-event-paris) in Paris last Spring I had made this one:
![58da19bd70642796203728](https://user-images.githubusercontent.com/4701338/33668269-8cde5c16-da9f-11e7-8104-8184bb5f285b.png)
[MeetTheNodes 2017 SVG.zip](https://github.com/godotengine/godot-design/files/1535613/MeetTheNodes.2017.SVG.zip)

It would be good to have something good looking for GodotCon 2018, which seems both friendly and professional. We don't have much time (I would like to post about GodotCon ASAP, actually tonight :D), so for the first iteration it could be kept simple like the GodotCon 2017 artwork, and maybe improved later on.

For info, the font used in the Godot logo and in the first image for "GODOTCON" is Lilita One.

(*) I doubt we can have something done by tonight, so I might go for a non-descript Godot 3.0 screenshot for this first blog post. There will be other posts in coming weeks to give more info about the venue we'll have selected, the talks that will be held, etc., so we'll be able to use the official artwork then.

**Comment by akien-mga** [comment]
> I would like to post about GodotCon ASAP, actually tonight :D

Actually make that tomorrow or (at the latest) Friday, Juan just posted another blog post so I don't want to post one the same day that would steal the focus.

**Comment by akien-mga** [comment]
CC @djrm @NathanLovato though I know you guys are busy :)

I need to publish something today though, so I'll hack something by stealing a nice screenshot from @fracteed to have some eye candy - a proper GodotCon banner can come later.

**Comment by QbieShay** [comment]
Hey, today I did this. I think i reached the maximum of my artistic capabilities, so please feel free to make it Godot-worthy :D
(Fonts: Signika, Lilita One)
[GodotxFOSDEM.zip](https://github.com/godotengine/godot-design/files/1549487/GodotxFOSDEM.zip)

![gfxbru](https://user-images.githubusercontent.com/7917475/33855222-94f069c0-dec4-11e7-9069-46476da2240a.png)

**Comment by djrm** [comment]
i made a godot con banner. it still needs some text and details, but i think its on the right track, considering the potential material for this year. I cant do another one for FOSDEM if needed.

ping @akien-mga 

![godot_con_2018](https://user-images.githubusercontent.com/1103897/34241095-b0c53926-e5d8-11e7-9cd8-d6cecb3887f1.png)

**Comment by djrm** [comment]
This is a more polished (near final?) version of the banner.

@akien-mga if you need the SVG i can push it to the repo, but i wanted to show it first

![godot_con_2018](https://user-images.githubusercontent.com/1103897/34506545-7e700f8a-eff3-11e7-8124-4581d43e13fd.png)
